name: giraffe_spotter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  freezed: ^1.1.1
  equatable: ^2.0.2
  json_annotation: ^4.4.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.5
  animations: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_svg: ^1.0.0
  delayed_display: ^2.0.0
  xml: ^5.1.0
  xml2json: ^5.0.0
  cached_network_image: ^3.0.0
  youtube_player_flutter: ^8.0.0
  url_launcher: ^6.0.6
  flutter_fimber: ^0.6.3
  share: ^2.0.4
  mapbox_gl: ^0.14.0
  location: ^4.3.0
  mapbox_search: ^3.0.1+2
  data_connection_checker: ^0.3.4
  formz: ^0.4.0
  pedantic: ^1.11.1
  open_mail_app: ^0.4.2
  firebase_dynamic_links: ^2.0.5
  firebase_core: ^1.3.0
  intl: ^0.17.0
  flutter_native_splash: ^1.2.3
  frefresh: ^1.1.0
  flutter_smartlook: ^3.0.2
  vimeo_player_flutter: ^0.0.3+1
  geolocator: ^8.0.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  geocoding: ^2.0.1
  webview_flutter: ^2.3.1
  metadata: ^1.0.0
  image_picker: ^0.8.4+4
  exif: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed_annotation: ^1.1.0
  build_runner: ^2.1.7
  pretty_dio_logger: ^1.1.1
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Poppins-ExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-ExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family: Poppins-Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
